# -*- coding: utf-8 -*-
"""avoda_ass3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PvmYtn1srlhdzb-hX3e8cHBTGnZAVI4t

#1. Write multiple programs which illustrates iteration through various data structures which you learned till now?
"""

https://colab.research.google.com/drive/1PvmYtn1srlhdzb-hX3e8cHBTGnZAVI4t?usp=sharing

String = "Welcome to python"
print("Creating String: ")
print(String)
     
# Printing First character
print("\nFirst character of String is: ")
print(String[0])
     
# Printing Last character
print("\nLast character of String is: ")
print(String[-1])
# Printing the length and type 
print(len(String))
print(type(String))
# Printing reverse of the string
print(String[::-1])

# Creating a List with
# the use of multiple values
List = ["Welocome", "To", "Python"]
print("\nList containing multiple values: ")
print(List)
 
# Creating a Multi-Dimensional List
# (By Nesting a list inside a List)
List2 = [['Welocome', 'To'], ['Python']]
print("\nMulti-Dimensional List: ")
print(List2)
 
# accessing a element from the 
# list using index number
print("Accessing element from the list")
print(List[0]) 
print(List[2])
 
# accessing a element using
# negative indexing
print("Accessing element using negative indexing")
     
# print the last element of list
print(List[-1])
     
# print the third last element of list 
print(List[-3])

Tuple = ('Welcome', 'Python')
print("\nTuple with the use of String: ")
print(Tuple)
     
# Creating a Tuple with
# the use of list
list1 = [1, 2, 4, 5, 6]
print("\nTuple using List: ")
Tuple = tuple(list1)
 
# Accessing element using indexing
print("First element of tuple")
print(Tuple[0])
 
# Accessing element from last
# negative indexing
print("\nLast element of tuple")
print(Tuple[-1])
   
print("\nThird last element of tuple")
print(Tuple[-3])

# Creating a Dictionary
Dict = {'Name': 'Python', 1: [1, 2, 3, 4]}
print("Creating Dictionary: ")
print(Dict)
 
# accessing a element using key
print("Accessing a element using key:")
print(Dict['Name'])
 
# accessing a element using get()
# method
print("Accessing a element using get:")
print(Dict.get(1))
 
# creation using Dictionary comprehension
myDict = {x: x**2 for x in [1,2,3,4,5]}
print(myDict)

"""# 2. Receive an input text from the user and print all letters except ‘e’ and ‘s’ by using for loop?"""

s=input()
l=['e','s']
for i in s:
  if i not in  l:
    print(i,end='')

"""# 3. Return sum of first n numbers with the help of for loop and range function?"""

n=int(input())
sum=0
for i in range(n+1):
    sum=sum+i
print(f"sum of first {n} naturanl numbers is {sum}")

"""# 4. Accept a number from the user and return Sum of all natural numbers that are multiples of 5,7 less than the number entered by the user.Eg:Input:20 -5,7,10,14,15 and sum=51?"""

#4

n=int(input())
sum=0
for i in range(n):
    if(i%5==0) or (i%7==0):
        sum=sum+i
        
print("Sum of natural number mutiple of 5 and 7 is  :",sum)